name: Build

on: push

jobs:
  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.RELEASE_TAG }}
      - uses: crystal-lang/install-crystal@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build and package
        run: |
          shards build --release --static --no-debug
          (Get-FileHash ./bin/ingraham.exe).Hash | Out-File ./bin/checksums.txt
          Compress-Archive -Path ./bin/* -DestinationPath ingraham-windows-amd64.zip
      - uses: actions/upload-artifact@v7
        with:
          name: windows
          path: ingraham-windows-amd64.zip
          if-no-files-found: error