name: Build

on: push

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.21-alpine
    steps:
      - uses: actions/checkout@v6
      - name: Build and package
        run: |
          mkdir -p bin
          shards install
          shards build --release --static --no-debug
          mb bin/ingraham bin/instagam-linux-amd64
      - uses: actions/upload-artifact@v7
        with:
          name: linux-amd64
          path: bin/ingraham-linux-amd64
          if-no-files-found: error
  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.RELEASE_TAG }}
      - uses: crystal-lang/install-crystal@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build and package
        run: |
          shards install
          shards build --release --static --no-debug
          Rename-Item -Path bin/ingraham.exe -NewName ingraham-windows-amd64.exe
      - uses: actions/upload-artifact@v7
        with:
          name: windows-amd64
          path: bin/ingraham-windows-amd64.exe
          if-no-files-found: error